### ISSUE TITLE
Help With Setup

### ISSUE THREAD

**Issue by V3L** [apexad/homebridge-sensor-cmd#1]
I am trying to get this to populate with two different values, so I can identify if a week of the year is even or odd. I have set the plugin up like this:

```
{
    "accessory": "SensorCmd",
    "name": "weekOddOrEven",
    "command": "oddOrEven.sh"
}

```
Then the oddOrEven.sh script is placed in the root of my homebridge directory and contains the following data:
```
#!/bin/bash
WEEK=`date +"%V"`
if [ $(($WEEK%2)) -eq 0 ];
then
    echo "even";
else
    echo "odd";
fi
```

If I replaced the even/odd text with the accepted states for a contact sensor, would the above work?

Also, do you know what the available states are for a contact sensor?

Thanks,
Vel

**Comment by apexad** [comment]
https://developers.homebridge.io/#/characteristic/ContactSensorState
So, accepted states are CONTACT_DETECTED (which is 0) and CONTACT_NOT_DETECTED (which is 1)
So, to be clear just change it to echo 0/echo 1

**Comment by V3L** [comment]
> https://developers.homebridge.io/#/characteristic/ContactSensorState
> So, accepted states are CONTACT_DETECTED (which is 0) and CONTACT_NOT_DETECTED (which is 1)
> So, to be clear just change it to echo 0/echo 1

Thanks for your quick reply, unfortunately the status doesn't seem to change. I've tried:
```
#!/bin/bash
WEEK=`date +"%V"`
if [ $(($WEEK%2)) -eq 0 ];
then
    echo 0;
else
    echo 1;
fi
```

and

```
#!/bin/bash
WEEK=`date +"%V"`
if [ $(($WEEK%2)) -eq 0 ];
then
    echo 1;
else
    echo 0;
fi
```

In the Homebridge UI, the status always shows as Closed. Do you have any idea what I could be missing? Is there a way to change the logging so I can see if the file is actually being called? As I am thinking maybe I have an issue with how I am referencing the shell script to be called.

Thanks,
Vel

**Comment by apexad** [comment]
Use the full path to the file like /var/lib/homebridge/oddOrEven.sh
