### ISSUE TITLE
support different sensor types

### ISSUE THREAD

**Issue by ME-64** [apexad/homebridge-sensor-cmd#2]
first of all thanks for the plugin, exactly what I was looking for. 

Is there any chance you could add an option to change the sensor type, i.e. to motion sensor or otherwise.

Thanks!

**Comment by apexad** [comment]
I realizes it's been over a year since you made the request.  I've also seriously messed up the versions for this plugin (it's a long story), but it is done.  2.50.5 will do what you want as you can now specify a "type".
